// sync-mcp.mjs — read the real MCP servers from ~/.claude.json and generate
// src/mcp-servers.generated.js for AI Tools OS.
//
// Run:  npm run sync
//
// Safety: this NEVER reads env *values* — only the env key names are surfaced
// (as a redacted "secrets" capability). No tokens or secrets are written to disk.
// Live tool counts / status come from Claude Code's runtime (not the config file),
// so they are seeded from a small known map below; re-run sync after `claude /mcp`
// to refresh.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "src", "mcp-servers.generated.js");
const CONFIG = join(homedir(), ".claude.json");

// Pretty display names (fallback: title-case the id).
const NAMES = {
  context7: "Context7",
  "desktop-commander": "Desktop Commander",
  filesystem: "Filesystem",
  firecrawl: "Firecrawl",
  github: "GitHub",
  memory: "Memory",
  playwright: "Playwright",
  puppeteer: "Puppeteer",
  tradingview: "TradingView",
};

// Per-server metadata: live tool counts (from `claude /mcp`), risk, capabilities,
// and a short description. Unknown servers fall back to DEFAULT_META.
const META = {
  context7:           { tools: 2,  risk: "low",  caps: ["network"],                        desc: "Up-to-date docs for any library, framework, or SDK." },
  "desktop-commander":{ tools: 26, risk: "crit", caps: ["files", "writes", "shell", "broad-fs"], desc: "Terminal control + full filesystem access on this machine." },
  filesystem:         { tools: 14, risk: "high", caps: ["files", "writes", "broad-fs"],     desc: "Read & write files across ~/, Documents and Desktop." },
  firecrawl:          { tools: 20, risk: "med",  caps: ["network", "secrets", "external"],  desc: "Web scraping, crawling, search and extraction." },
  github:             { tools: 26, risk: "low",  caps: ["network", "secrets"],              desc: "Repos, issues, PRs, Actions and code search." },
  memory:             { tools: 9,  risk: "low",  caps: ["files", "writes"],                 desc: "Local knowledge-graph memory store." },
  playwright:         { tools: 23, risk: "med",  caps: ["network", "shell", "files"],       desc: "Headless browser automation and scraping." },
  puppeteer:          { tools: 8,  risk: "med",  caps: ["network", "shell", "files"],       desc: "Chrome automation via Puppeteer." },
  tradingview:        { tools: 81, risk: "med",  caps: ["network", "files"],                desc: "Live TradingView chart control & market data." },
};
const DEFAULT_META = { tools: 0, risk: "low", caps: ["network"], desc: "Model Context Protocol server." };

const titleCase = (id) =>
  id.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

const estTokens = (tools) => Math.round((tools * 180 + 500) / 100) * 100;

function buildCmd(cfg) {
  if (cfg.url) return cfg.url;
  const args = Array.isArray(cfg.args) ? cfg.args : [];
  return [cfg.command, ...args].filter(Boolean).join(" ");
}

function main() {
  const raw = JSON.parse(readFileSync(CONFIG, "utf8"));
  const servers = raw.mcpServers || {};
  const ids = Object.keys(servers).sort();

  const list = ids.map((id) => {
    const cfg = servers[id];
    const meta = META[id] || DEFAULT_META;
    const envKeys = Object.keys(cfg.env || {});
    // surface secret usage without ever touching values
    const caps = [...meta.caps];
    if (envKeys.length && !caps.includes("secrets")) caps.push("secrets");

    return {
      id,
      name: NAMES[id] || titleCase(id),
      scope: "user", // all live in ~/.claude.json
      state: "running",
      enabled: true,
      risk: meta.risk,
      tokens: estTokens(meta.tools),
      tools: meta.tools,
      transport: cfg.type || (cfg.url ? "sse" : "stdio"),
      cmd: buildCmd(cfg),
      uptime: "active",
      desc: meta.desc,
      caps,
      errors: 0,
      latency: 12,
      env: envKeys, // KEY NAMES ONLY — never values
    };
  });

  const banner =
    `// AUTO-GENERATED by scripts/sync-mcp.mjs from ~/.claude.json — do not edit by hand.\n` +
    `// Run \`npm run sync\` to refresh. Contains NO secret values (only env key names).\n` +
    `// Synced: ${new Date().toISOString()}\n\n`;

  const body = `export const MCPS = ${JSON.stringify(list, null, 2)};\n`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, banner + body);
  console.log(`Synced ${list.length} MCP servers → src/mcp-servers.generated.js`);
  for (const m of list) console.log(`  • ${m.name.padEnd(18)} ${String(m.tools).padStart(2)} tools · ${m.risk}`);
}

main();
