import React, { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { Button, Field, Notice, Dialog } from './workbench-ui.jsx';
import { request, contextEstimate, copyText } from './api.js';
import { aiRequest, useAIJob, AIControls, settingsFromPreferences } from './ai.jsx';
import { Icon } from './icons.jsx';
import './experience.css';

export const compactPath = path => String(path || '').split('/').filter(Boolean).slice(-2).join('/');
const num = n => Number.isFinite(n) ? n.toLocaleString() : 'Not reported';
const when = date => date ? new Date(date).toLocaleString() : 'Not recorded';
const terminal = job => !job || ['completed', 'failed', 'canceled', 'interrupted'].includes(job.status);
export function useInsights(resources = []) {
  const resourceRef = useRef(resources); resourceRef.current = resources;
  const [state, setState] = useState({ sessions: [], recommendations: [] }), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const active = useRef(false), alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const refresh = useCallback(async (offset = 0) => {
    if (active.current) return; active.current = true; setBusy(true); setError('');
    try { const value = await aiRequest('insights.sessions', { offset, resources: resourceRef.current.filter(r => r.kind === 'mcp').map(({ id, name, kind, provider, scope, project, enabled, parked, error, overrideOnly }) => ({ id, name, kind, provider, scope, project, enabled, parked, error, overrideOnly })) }); if (alive.current) setState(value); }
    catch (e) { if (alive.current) setError(e.message); } finally { active.current = false; if (alive.current) setBusy(false); }
  }, []);
  return { ...state, busy, error, refresh };
}
export function ResourceLibrary({ items, busy, showDetails, edit, enhance, action, review, recommendations = [] }) {
  const [sort, setSort] = useState('name'), [state, setState] = useState('all'), [ids, setIds] = useState([]), [limit, setLimit] = useState(50);
  const filtered = useMemo(() => items.filter(r => state === 'all' || state === 'enabled' && r.enabled || state === 'disabled' && !r.enabled || state === 'issues' && r.error)
    .sort((a, b) => sort === 'size' ? (b.estimatedTokens || 0) - (a.estimatedTokens || 0) : sort === 'modified' ? String(b.modifiedAt || '').localeCompare(a.modifiedAt || '') : a.name.localeCompare(b.name)), [items, state, sort]);
  const selected = filtered.filter(r => ids.includes(r.id) && !r.parked && !r.error);
  useEffect(() => { setLimit(50); }, [state, sort, items]);
  return <div className="resource-library">
    <div className="library-toolbar"><span>{filtered.length} resources</span><Field label="Status"><select aria-label="Resource status" value={state} onChange={e => setState(e.target.value)}><option value="all">All states</option><option value="enabled">Enabled</option><option value="disabled">Disabled / archived</option><option value="issues">Needs attention</option></select></Field><Field label="Sort"><select aria-label="Sort resources" value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name A–Z</option><option value="modified">Recently changed</option><option value="size">Largest text first</option></select></Field>
      <Button onClick={() => setIds(filtered.filter(r => !r.parked && !r.error).slice(0, 1000).map(r => r.id))}>Select matching</Button><Button disabled={!ids.length} onClick={() => setIds([])}>Clear</Button></div>
    {!!selected.length && <div className="selection-bar"><strong>{selected.length} selected</strong><Button primary onClick={() => review(selected)}>Review with AI</Button><Button disabled={selected.length > 100} onClick={() => action('cleanup', selected)}>Clean up selection</Button>{selected.length > 100 && <span>Clean up up to 100 resources at a time.</span>}</div>}
    {!filtered.length && <div className="empty-state"><Icon name="search" size={32} /><h2>A little breathing room</h2><p>No resources match these filters. Try another scope or add a project in Settings.</p></div>}
    <div className="wb-list">{filtered.slice(0, limit).map(r => {
      const recommendation = recommendations.find(a => a.resourceId === r.id);
      return <article className={`wb-resource resource-${r.kind}`} key={r.id + (r.parked ? '-parked' : '')}>
        <label className="resource-select"><input aria-label={`Select ${r.name}`} type="checkbox" disabled={r.parked || !!r.error} checked={selected.some(x => x.id === r.id)} onChange={e => setIds(e.target.checked ? [...new Set([...ids, r.id])] : ids.filter(id => id !== r.id))} /></label>
        <div className="resource-body"><div className="resource-heading"><button className="wb-resource-name" onClick={() => edit(r)}>{r.name}</button><span className={`state-dot ${r.enabled ? 'enabled' : ''}`} title={r.enabled ? 'Configured' : 'Disabled'} /></div>
          <p className="resource-description">{r.description || (r.kind === 'mcp' ? `${r.transport || 'Native'} tool connection` : r.kind === 'memory' ? 'Instructions that guide your AI workspace' : `Your ${r.kind === 'agents' ? 'subagent' : r.kind === 'config' ? 'configuration' : r.kind} resource`)}</p>
          <div className="resource-meta"><span>{r.provider}</span><span>{r.nativeScope || r.scope}</span>{r.project && <span title={showDetails ? r.project : undefined}>{compactPath(r.project)}</span>}<span>{r.readonly ? 'Read-only' : r.archived ? 'Archived' : r.enabled ? 'Enabled' : 'Disabled'}</span></div>
          {recommendation && <p className="resource-nudge">◌ No recorded use in 3 sessions <button onClick={() => action('sessions')}>See evidence</button></p>}
          {r.error && <Notice error={!r.metadataWarning}>{r.error}</Notice>}
          <details className="resource-details" open={showDetails || undefined}><summary>Details</summary><p className="wb-path">{r.path}</p><p>{r.estimatedTokens != null ? `~${num(r.estimatedTokens)} text tokens · ` : ''}{r.modifiedAt ? `Changed ${when(r.modifiedAt)}` : ''}</p>{r.kind === 'mcp' && <p>Runtime connection unknown{r.hasSecrets ? ' · Credential fields present' : ''}. Providers decide loading and trust.</p>}</details>
        </div><div className="wb-resource-actions"><Button disabled={busy || !!r.error && r.readonly} onClick={() => edit(r)}>Read / edit</Button>
          {!r.readonly && !r.parked && !r.error && !['mcp', 'plugins'].includes(r.kind) && <Button disabled={busy} onClick={() => enhance(r)}>Enhance with AI</Button>}
          <details className="action-menu"><summary aria-label={`More actions for ${r.name}`}>•••</summary><div>
            {!r.readonly && !r.parked && !r.error && !['mcp', 'plugins'].includes(r.kind) && <Button disabled={busy} onClick={() => action('enhance-options', r)}>Enhance with options</Button>}
            {!r.readonly && ['mcp', 'plugins', 'skills', 'commands', 'agents'].includes(r.kind) && <Button disabled={busy} aria-label={`${r.enabled ? 'Disable' : 'Restore'} ${r.name} from ${r.path}`} onClick={() => action('toggle', r)}>{r.enabled ? 'Disable' : 'Restore'}</Button>}
            {!r.readonly && !r.error && !r.overrideOnly && ['mcp', 'plugins', 'skills', 'commands', 'agents', 'memory'].includes(r.kind) && <Button disabled={busy} onClick={() => action('transfer', r)}>Copy / move</Button>}
            {r.kind === 'mcp' && !r.readonly && !r.parked && <Button disabled={busy} onClick={() => action('mcp-project', r)}>Project access</Button>}
            {!r.readonly && !['mcp', 'plugins', 'config'].includes(r.kind) && r.enabled && <Button disabled={busy} onClick={() => action('cleanup', [r])}>Archive</Button>}
            {!r.enabled && !['mcp', 'plugins', 'skills', 'commands', 'agents'].includes(r.kind) && <Button disabled={busy} onClick={() => action('toggle', r)}>Restore</Button>}
            <Button disabled={busy || !!r.error} onClick={() => action('share', r)}>Export</Button>
          </div></details>
        </div></article>;
    })}</div>
    {filtered.length > limit && <Button onClick={() => setLimit(n => n + 50)}>Show 50 more ({filtered.length - limit} remaining)</Button>}
  </div>;
}
export function BulkReviewDialog({ resources, preferences, close, edit }) {
  const [settings, setSettings] = useState(() => settingsFromPreferences(preferences)), [focus, setFocus] = useState('Find unclear instructions, duplication, excessive length, misplaced project guidance and security issues. Recommend specific minimal fixes.'), [advanced, setAdvanced] = useState(false);
  const state = useAIJob(), result = state.job?.result;
  const [copyError, setCopyError] = useState('');
  const tokens = resources.reduce((n, r) => n + (r.estimatedTokens || 0), 0);
  return <Dialog title={`Review ${resources.length} resources`} wide close={close}>
    <div className="review-intro"><span className="feature-orb">✦</span><div><h3>A second pair of eyes for your workspace</h3><p>AI reviews the selected saved files and recommends changes. You decide what to apply.</p></div></div>
    <Notice>{resources.length} files · approximately {num(tokens)} source text tokens per full pass, plus instructions and answers. A whole-workspace review can use substantially more tokens than a per-file review. The run stops at your saved call/time and supported cost limits; partial results are retained.</Notice>
    <p>Using <strong>{settings.provider === 'auto' ? 'your first compatible engine' : settings.provider}</strong> · {settings.model || 'saved model preference or engine default'}</p>
    <div className="wb-actions"><Button primary disabled={!resources.length || resources.length > 1000 || state.busy} onClick={() => state.start('ai.reviewAll', { ids: resources.map(r => r.id), focus, settings })}>Start AI review</Button><Button disabled={state.busy} onClick={() => setAdvanced(!advanced)}>Choose engine & options</Button><Button disabled={!resources.length || state.busy} onClick={() => state.start('ai.reviewAll', { ids: resources.map(r => r.id), focus, settings: { ...settings, provider: 'local' } })}>Local checks</Button></div>
    {advanced && <div className="advanced-panel"><AIControls value={settings} change={setSettings} /><Field label="Review goal"><textarea value={focus} onChange={e => setFocus(e.target.value)} /></Field></div>}
    <details><summary>Selected files and scope</summary>{resources.map(r => <p key={r.id}>{r.name} · {r.provider} · {r.scope}</p>)}</details>
    {copyError && <Notice error>{copyError}</Notice>}{state.error && <Notice error>{state.error}</Notice>}{state.job && <p role="status">{state.job.status} · {state.job.progress}</p>}{state.job?.error && <Notice error>{state.job.error}</Notice>}{state.busy && <Button onClick={state.cancel}>Cancel review</Button>}
    {result && <><p>{result.summary}</p><p>{result.provenance} · {Number.isFinite(result.cost) ? `$${result.cost.toFixed(4)} reported` : 'Cost not reported / local checks'}</p>{!result.complete && <Notice>Partial review. Unprocessed files have no result.</Notice>}{result.findings?.map((f, i) => <article className="review-finding" key={i}><span className="wb-badge">{f.severity}</span><h3>{f.message}</h3><p>{f.suggestion}</p><details><summary>Evidence · line {f.line}</summary><pre>{f.evidence}</pre><p className="wb-path">{f.path}</p></details>{edit && <Button onClick={() => { const resource = resources.find(r => r.id === f.fileId); if (resource) edit(resource, f.suggestion || f.message); }}>Review file & enhance</Button>}</article>)}{terminal(state.job) && <Button onClick={async () => { try { await copyText(JSON.stringify(result, null, 2)); setCopyError(''); } catch (e) { setCopyError(e.message); } }}>Copy review report</Button>}</>}
  </Dialog>;
}
export function CleanupDialog({ resources, run, close }) {
  const [preview, setPreview] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [reviewed, setReviewed] = useState(false);
  const eligible = resources.filter(r => r.enabled && !r.parked && !r.readonly && !r.error && !r.overrideOnly && ['mcp', 'skills', 'memory', 'commands', 'agents'].includes(r.kind));
  const sources = eligible.map(r => ({ id: r.id, revision: r.revision }));
  const load = async () => { setError(''); setPreview(null); setReviewed(false); try { setPreview(await request('cleanup.preview', { sources })); } catch (e) { setError(e.message); } };
  useEffect(() => { void load(); }, []);
  return <Dialog title="Review cleanup" wide close={() => { if (!busy) close(); }}><p>Selected MCP definitions will be disabled. Instruction resources will be archived with their complete files and can be restored from their resource page. Restart the harness session for changes to take effect.</p>
    {eligible.length !== resources.length && <Notice>{resources.length - eligible.length} ineligible resources excluded. Read-only, disabled and unsupported sources cannot be cleaned up here.</Notice>}
    {error && <Notice error>{error}</Notice>}{preview?.sources.map(r => <article className="wb-card" key={r.id}><strong>{r.name}</strong><p>{r.action} · {r.provider} · {r.scope}</p><p className="wb-path">{r.path}</p></article>)}
    {preview && <><label className="wb-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed these changes and their scopes</label><Button primary disabled={!reviewed || busy} onClick={async () => { setBusy(true); setError(''); try { await run('cleanup.apply', { sources, previewRevision: preview.previewRevision }); close(); } catch (e) { setError(e.message); setReviewed(false); } finally { setBusy(false); } }}>Apply cleanup</Button></>}<Button disabled={busy} onClick={load}>Refresh preview</Button>
  </Dialog>;
}
export function SessionsPage({ insights, provider, project, scope, search, resources }) {
  const [selectedId, setSelectedId] = useState(null), [sort, setSort] = useState('recent');
  const list = insights.sessions.filter(s => (provider === 'all' || s.provider === provider) &&
    (scope === 'all' || scope === 'user' && !s.project || scope === 'project' && s.project && (!project || s.project === project) || scope === 'folder' && project && (s.project === project || s.project?.startsWith(project.replace(/\/$/, '') + '/'))) &&
    (!search || [s.provider, s.model, s.project, s.nativeId].join(' ').toLowerCase().includes(search.toLowerCase())))
    .sort((a, b) => sort === 'context' ? (b.peakInputTokens || 0) - (a.peakInputTokens || 0) : String(b.lastActiveAt || b.modifiedAt).localeCompare(a.lastActiveAt || a.modifiedAt));
  const selected = list.find(s => s.id === selectedId) || list[0];
  return <><div className="page-lead"><div><h2>See what happened inside a session</h2><p>Local activity, tool use and context evidence, without retaining your conversations.</p></div><Button disabled={insights.busy} onClick={() => insights.refresh()}>{insights.busy ? 'Reading history…' : 'Refresh sessions'}</Button></div>
    {insights.error && <Notice error>{insights.error}</Notice>}{insights.paused && <Notice>Session insight is paused. Enable it in Settings to read local session metadata.</Notice>}
    <div className="session-metrics"><div><strong>{list.length}</strong><span>sessions in view</span></div><div><strong>{list.reduce((n, s) => n + s.toolCalls, 0)}</strong><span>recorded tool calls</span></div><div><strong>{list.filter(s => s.partial || s.coverage !== 'tool-events').length}</strong><span>limited coverage</span></div></div>
    <div className="session-workspace"><section className="session-list"><Field label="Sort sessions"><select value={sort} onChange={e => setSort(e.target.value)}><option value="recent">Most recent</option><option value="context">Highest observed input</option></select></Field>
      {!list.length && <p>No local sessions match this view. Refresh or broaden the filters.</p>}
      {list.map(s => <button className={`session-item ${selected?.id === s.id ? 'selected' : ''}`} key={s.id} onClick={() => setSelectedId(s.id)}><span className="session-provider">{s.provider}{s.subagent ? ' · subagent' : ''}</span><strong>{compactPath(s.project) || 'Workspace not recorded'}</strong><small>{when(s.lastActiveAt || s.modifiedAt)}</small><span>{s.coverage === 'messages-only' ? 'Tool use unavailable' : `${s.toolCalls} recorded calls`} · {s.partial ? 'Partial' : s.completed ? 'Turn completed' : 'End not confirmed'}</span></button>)}
      {insights.nextOffset != null && <Button disabled={insights.busy} onClick={() => insights.refresh(insights.nextOffset)}>Load older sessions</Button>}
    </section>{selected && <section className="session-detail" key={selected.id}>
      <div className="section-eyebrow">SESSION INSIGHT</div>{selected.partial && <Notice>Partial history. Some records are missing from this view; counts cover only the records read. Non-use alerts exclude this session.</Notice>}<h2>{selected.model || selected.provider}</h2><p>{compactPath(selected.project) || 'Workspace unavailable'} · {selected.turns} recorded prompts</p>
      <div className="context-hero"><strong>{num(selected.latestInputTokens)}</strong><span>latest recorded input tokens</span>{selected.contextWindow != null && <><progress max={selected.contextWindow} value={selected.latestInputTokens || 0} aria-label="Latest input against context capacity" /><p>{selected.latestInputTokens == null ? 'Usage unavailable' : `${(selected.latestInputTokens / selected.contextWindow * 100).toFixed(1)}%`} of {num(selected.contextWindow)} reported context capacity</p></>}
      <p>Input footprint at a model request. Output, reserves and harness accounting may make the harness’s context percentage differ.</p></div>
      <div className="session-stats"><div><strong>{num(selected.firstInputTokens)}</strong><span>first request, including prompt</span></div><div><strong>{num(selected.peakInputTokens)}</strong><span>peak recorded input</span></div><div><strong>{num(selected.totalTokens)}</strong><span>cumulative reported tokens</span></div><div><strong>{selected.compactions}</strong><span>recorded compactions</span></div></div>
      {!!selected.timeline.length && <section><h3>Input across requests</h3><div className="token-timeline" aria-label="Recorded input timeline">{selected.timeline.slice(-80).map((p, i) => <div key={i} title={`${when(p.at)} · ${num(p.inputTokens)} input tokens`} style={{ height: `${Math.max(3, p.inputTokens / (selected.peakInputTokens || 1) * 100)}%` }} />)}</div><details><summary>Read timeline values</summary><table><thead><tr><th>Time</th><th>Input</th><th>Output</th></tr></thead><tbody>{selected.timeline.map((p, i) => <tr key={i}><td>{when(p.at)}</td><td>{num(p.inputTokens)}</td><td>{num(p.outputTokens)}</td></tr>)}</tbody></table></details></section>}
      <section>{selected.reportedContext && <><h3>Provider context observation</h3><p>{num(selected.reportedContext.tokens)} context tokens · {num(selected.reportedContext.percent)}% · {selected.reportedContext.phase} at {when(selected.reportedContext.at)}</p></>}<h3>Before the first prompt</h3><p>Exact startup tokens: <strong>{num(selected.startupTokens)}</strong>. Most transcripts begin after a prompt is submitted.</p>{selected.startupEstimate && <p>~{num(selected.startupEstimate.tokens)} tokens in recorded system prompt text (characters ÷ 4). {selected.startupEstimate.includes}</p>}<p>{selected.availableTools.filter(t => t.phase === 'first request').length || 'No'} tool names recorded for the first request. Deferred schemas are labeled separately below.</p></section>
      <section><h3>Tools available & used</h3><p>{selected.availableTools.length || 'Unknown'} observed tool names · {selected.coverage === 'messages-only' ? 'Calls not reported' : `${selected.tools.length} distinct tools called`}</p>
        {selected.tools.slice(0, 50).map(t => <div className="wb-row" key={t.name}><span>{t.name}</span><strong>{t.calls} calls</strong></div>)}
        <details><summary>Availability evidence ({selected.availableTools.length})</summary>{selected.availableTools.map(t => <div className="wb-row" key={t.name}><span>{t.name}</span><small>{t.loading} · {t.phase}</small></div>)}</details>
      </section><section><h3>Skills & memory evidence</h3>{!selected.resources.length && <p>The log does not enumerate loaded instruction files.</p>}{selected.resources.map((r, i) => <div className="wb-row" key={i}><span>{compactPath(r.name)}<small className="wb-muted"> · {r.kind}</small></span><span>{r.phase}{r.estimatedTokens != null ? ` · ~${num(r.estimatedTokens)} tokens` : ''}</span></div>)}</section>
      <details><summary>Current configuration for this workspace</summary><p>This is today’s inventory, not a reconstruction of the session’s configuration.</p>{resources.filter(r => r.provider === selected.provider && r.enabled && (r.scope === 'user' || r.project && (r.project === selected.project || selected.project?.startsWith(r.project + '/')))).map(r => <p key={r.id}>{r.name} · {r.kind} · {r.scope}</p>)}</details>
      <details><summary>Source & coverage</summary><p className="wb-path">{selected.path}</p><p>Session: {selected.nativeId || 'Not reported'} · {selected.coverage}</p>{selected.notes.map(n => <p key={n}>{n}</p>)}</details>
    </section>}</div>{insights.issues?.map((i, n) => <Notice key={n}>{i.message}</Notice>)}</>;
}
export function ContextExplorer({ resources, insights, navigate, edit }) {
  const estimate = contextEstimate(resources), groups = ['memory', 'skills', 'agents', 'commands'].map(kind => ({ kind, files: estimate.files.filter(r => r.kind === kind) })).map(g => ({ ...g, tokens: g.files.reduce((n, r) => n + r.estimatedTokens, 0) }));
  const latest = [...insights.sessions].sort((a, b) => String(b.lastActiveAt || b.modifiedAt).localeCompare(a.lastActiveAt || a.modifiedAt)).find(s => s.latestInputTokens != null && !s.partial);
  return <><div className="page-lead"><div><h2>Make room for the work that matters</h2><p>Understand your instruction footprint and inspect what a session actually reported.</p></div><Button onClick={() => navigate('sessions')}>Explore sessions</Button></div>
    <div className="context-grid"><section className="context-map"><div className="section-eyebrow">SELECTED LOCAL TEXT</div><strong className="display-number">~{num(estimate.tokens)}</strong><p>estimated tokens across {estimate.files.length} distinct instruction files</p><div className="context-stack">{groups.filter(g => g.tokens).map((g, i) => <div key={g.kind} style={{ flex: g.tokens, background: `var(--chart-${i})` }} title={`${g.kind}: ${num(g.tokens)} estimated tokens`} />)}</div><div className="context-legend">{groups.map((g, i) => <div key={g.kind}><i style={{ background: `var(--chart-${i})` }} /><span>{g.kind}</span><strong>{num(g.tokens)}</strong></div>)}</div><p className="wb-muted">Characters ÷ 4. Full skill/agent bodies often load on demand. This inventory total is not startup context and excludes MCP schemas, conversation and system instructions.</p></section>
      <section className="context-live"><div className="section-eyebrow">MOST RECENT MEASUREMENT</div><strong className="display-number">{num(latest?.latestInputTokens)}</strong><p>{latest ? `${latest.provider} · latest input in a recorded session` : 'Read session history to see provider-reported input usage.'}</p><Button onClick={() => navigate('sessions')}>View evidence →</Button><div className="truth-labels"><span>● Measured: reported by harness</span><span>◐ Observed: present in a log</span><span>◌ Estimated: local text size</span></div></section></div>
    <section className="wb-card"><h2>Largest instruction files</h2><p>Good candidates for a clarity review. Size alone does not establish a problem.</p>{[...estimate.files].sort((a, b) => b.estimatedTokens - a.estimatedTokens).slice(0, 15).map(r => <div className="context-file" key={r.id}><button className="wb-resource-name" onClick={() => edit(r)}>{r.name}</button><span>{r.provider} · {r.scope}</span><div><i style={{ width: `${r.estimatedTokens / Math.max(1, ...estimate.files.map(f => f.estimatedTokens)) * 100}%` }} /></div><strong>~{num(r.estimatedTokens)}</strong></div>)}</section></>;
}
export function CleanupPage({ resources, insights, action, edit, review }) {
  const [tab, setTab] = useState('attention');
  const duplicates = Object.values(resources.filter(r => !r.parked && !r.error && r.revision && ['skills', 'memory', 'commands', 'agents'].includes(r.kind)).reduce((groups, r) => { (groups[`${r.kind}:${r.revision}`] ||= []).push(r); return groups; }, {})).filter(group => new Set(group.map(r => r.canonicalPath || r.path)).size > 1);
  const oversized = resources.filter(r => r.enabled && r.kind === 'memory' && ((r.lines || 0) > 500 || (r.estimatedTokens || 0) > 8000));
  const inactive = resources.filter(r => !r.enabled);
  const recommendations = insights.recommendations.filter(a => resources.some(r => r.id === a.resourceId));
  return <><div className="cleanup-hero"><span className="feature-orb">◌</span><div><h2>A lighter, more intentional workspace</h2><p>Review what’s unused, repeated or growing too large. Keep what helps. Archive what doesn’t.</p></div><Button onClick={() => review(resources.filter(r => !r.parked && !r.error && ['memory', 'skills'].includes(r.kind)))}>Find improvements with AI</Button></div>
    <div className="segmented" aria-label="Cleanup categories">{[['attention', 'Needs attention'], ['duplicates', `Duplicates · ${duplicates.length}`], ['archived', `Disabled / archived · ${inactive.length}`]].map(([key, name]) => <button key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{name}</button>)}</div>
    {tab === 'attention' && <>{!recommendations.length && !oversized.length && <div className="empty-state"><h2>No cleanup recommendations in this view</h2><p>Read session history to identify unused MCPs, or run a quality review to find instruction issues.</p><Button disabled={insights.busy} onClick={() => insights.refresh()}>Check session activity</Button></div>}{recommendations.map(a => <article className="cleanup-item" key={a.id}><span className="wb-badge">{a.confidence}</span><h3>{a.title}</h3><p>{a.message}</p><p className="wb-muted">{a.note}</p><div className="wb-actions"><Button onClick={() => action('cleanup', resources.filter(r => r.id === a.resourceId))}>Review disable</Button><Button onClick={() => action('transfer', resources.find(r => r.id === a.resourceId))}>Move to a project</Button><Button onClick={() => action('sessions')}>Session evidence</Button><Button onClick={() => action('dismiss', a)}>Dismiss for these sessions</Button></div></article>)}
      {oversized.map(r => <article className="cleanup-item" key={r.id}><span className="wb-badge">Large memory file</span><h3>{r.name}</h3><p>{r.lines ? `${num(r.lines)} lines · ` : ''}~{num(r.estimatedTokens)} estimated text tokens. Review for duplication and separate detailed project procedures when appropriate.</p><Button onClick={() => review([r])}>Review this file</Button><Button onClick={() => edit(r)}>Read file</Button></article>)}</>}
    {tab === 'duplicates' && <><Notice>Matching contents can be intentional across tools or projects. Review scope before archiving a copy. Support files in skill folders may differ even when SKILL.md matches.</Notice>{!duplicates.length && <p>No exact instruction-file duplicates found.</p>}{duplicates.map((group, i) => <article className="cleanup-item" key={i}><h3>{group.length} matching instruction files</h3>{group.map(r => <div className="wb-row" key={r.id}><span>{r.name} · {r.provider} · {r.scope} · {compactPath(r.project)}</span><div className="wb-actions"><Button onClick={() => edit(r)}>Inspect</Button><Button disabled={r.readonly || !r.enabled} onClick={() => action('cleanup', [r])}>Review archive</Button></div></div>)}</article>)}</>}
    {tab === 'archived' && <>{!inactive.length && <p>Your disabled and archived resources will appear here.</p>}{inactive.map(r => <div className="wb-row" key={r.id}><span>{r.name} · {r.provider} · {r.scope}</span><div className="wb-actions"><Button onClick={() => edit(r)}>Inspect</Button><Button disabled={r.readonly} onClick={() => action('toggle', r)}>Restore</Button></div></div>)}</>}
  </>;
}
export function NewsCard({ preferences, savePreferences }) {
  const [data, setData] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [configure, setConfigure] = useState(false), [prompt, setPrompt] = useState(preferences.newsPrompt || ''), [preview, setPreview] = useState(null);
  const mounted = useRef(true);
  const refresh = useCallback(async (force = false) => { setBusy(true); setError(''); try { const r = await aiRequest('insights.news', { refresh: force }); if (mounted.current) setData(r); } catch (e) { if (mounted.current) setError(e.message); } finally { if (mounted.current) setBusy(false); } }, []);
  useEffect(() => { mounted.current = true; void refresh(); return () => { mounted.current = false; }; }, [refresh, preferences.newsPrompt, preferences.newsEnabled]);
  return <section className="news-card"><div className="section-heading"><div><div className="section-eyebrow">OFFICIAL SOURCES ONLY</div><h2>From your AI tools</h2></div><Button disabled={busy} onClick={() => void refresh(true)}>{busy ? 'Refreshing…' : 'Refresh'}</Button></div><p>Release headlines for detected harnesses and their model families.</p>
    <Button onClick={() => { setPrompt(preferences.newsPrompt || ''); setPreview(null); setConfigure(!configure); }}>Customize with a prompt</Button>
    {configure && <div className="news-config"><Field label="What news matters to you?"><textarea value={prompt} onChange={e => { setPrompt(e.target.value); setPreview(null); }} placeholder="Only Codex model releases from the last 30 days, exclude Cursor" /></Field><Button disabled={busy} onClick={async () => { try { setPreview((await aiRequest('insights.news.preview', { prompt })).filter); setError(''); } catch (e) { setError(e.message); } }}>Preview news preferences</Button>{preview && <><p>{preview.providers.join(', ') || 'No matching detected tools'} · {preview.types.join(' + ')} · last {preview.days} days</p><p className="wb-muted">{preview.explanation}</p><Button onClick={async () => { try { await savePreferences({ newsPrompt: prompt, newsEnabled: true }); setConfigure(false); } catch (e) { setError(e.message); } }}>Save news preferences</Button></>}</div>}
    {error && <Notice error>{error}</Notice>}{data?.paused && <p>Release news is paused in Settings.</p>}
    {data?.items?.slice(0, 6).map(item => <article className="news-item" key={item.id}><small>{item.source} · {new Date(item.publishedAt).toLocaleDateString()}</small><button onClick={async () => { try { const r = await window.aios.openLink(item.url); if (!r.ok) throw Error(r.error); } catch (e) { setError(e.message); } }}>{item.title}<span>↗</span></button></article>)}
    {data && !data.paused && !data.items?.length && <p>No matching release headlines in this time range.</p>}
    <details><summary>Freshness & sources</summary>{data?.sources?.map(s => <p key={s.source}>{s.source}: {s.fetchedAt ? `fetched ${when(s.fetchedAt)}` : 'not fetched'}{s.stale ? ' · cached / offline' : ''}{s.error ? ` · ${s.error}` : ''}</p>)}<p>News never sends your files or prompts to a publisher. Only these official feeds are fetched.</p></details>
  </section>;
}
export function Overview({ data, resources, insights, navigate, review, preferences, savePreferences, children }) {
  const instructions = resources.filter(r => !r.parked && !r.error && ['skills', 'memory'].includes(r.kind)), engines = [...new Set(resources.map(r => r.provider))];
  const recent = [...insights.sessions].sort((a, b) => String(b.lastActiveAt || b.modifiedAt).localeCompare(a.lastActiveAt || a.modifiedAt)).slice(0, 3), findings = insights.recommendations.filter(a => resources.some(r => r.id === a.resourceId));
  return <><section className="workspace-hero"><div><div className="section-eyebrow">ONE WORKSPACE. EVERY AI TOOL.</div><h2>A clear view.<br /><em>A better starting point.</em></h2><p>Keep your tools organized, your instructions useful, and your attention on the work.</p><div className="wb-actions"><Button primary onClick={() => navigate('cleanup')}>Clean up workspace</Button><Button onClick={() => navigate('sessions')}>Explore session context →</Button></div></div><div className="workspace-orbit" aria-hidden="true"><span className="orbit-core">AIOS</span>{['Claude', 'Codex', 'Cursor'].map((p, i) => <span key={p} className={`orbit-node node-${i}`}>{p}</span>)}</div></section>
    <div className="overview-pulse"><button onClick={() => navigate('skills')}><strong>{resources.length}</strong><span>local resources</span></button><button onClick={() => navigate('tools')}><strong>{engines.length}</strong><span>harnesses represented</span></button><button onClick={() => navigate('settings')}><strong>{data.projects.length}</strong><span>project folders</span></button><button className={findings.length ? 'pulse-attention' : ''} onClick={() => navigate('cleanup')}><strong>{findings.length}</strong><span>usage recommendations</span></button></div>
    <div className="overview-columns"><div className="overview-primary"><section className="ai-checkup"><div className="section-eyebrow">WORKSPACE CHECKUP</div><h2>Give your instructions a fresh perspective</h2><p>Review {instructions.length} skills and memory files across the selected scopes. Find duplication, unclear instructions and misplaced project guidance.</p><Button primary disabled={!instructions.length} onClick={() => review(instructions)}>Review skills & memory with AI</Button><p className="wb-muted">A broad review uses more model tokens. You’ll see the file count and estimated text size before starting. Per-file and multi-select reviews are available in each resource page.</p></section>
      <section className="activity-card"><div className="section-heading"><div><div className="section-eyebrow">SESSION ACTIVITY</div><h2>Understand the context behind the answer</h2></div><Button disabled={insights.busy} onClick={() => insights.refresh()}>{insights.busy ? 'Reading…' : 'Read sessions'}</Button></div>
        {!recent.length && <p>Inspect local session metadata to see input usage, tools called and instruction evidence. Conversation text stays out of the index.</p>}
        {recent.map(s => <button className="activity-row" key={s.id} onClick={() => navigate('sessions')}><span><strong>{s.provider}</strong><small>{compactPath(s.project) || 'Workspace not recorded'}</small></span><span>{s.latestInputTokens == null ? 'Usage unavailable' : `${num(s.latestInputTokens)} input tokens`}<small>{when(s.lastActiveAt || s.modifiedAt)}</small></span></button>)}{insights.error && <Notice>{insights.error}</Notice>}
      </section>{!!findings.length && <section className="home-nudge"><h3>{findings.length} {findings.length === 1 ? 'MCP deserves' : 'MCPs deserve'} a closer look</h3><p>No calls were recorded in their last three eligible sessions. Inspect availability evidence before disabling or changing scope.</p><Button onClick={() => navigate('cleanup')}>Review recommendations</Button></section>}
      {children}
    </div><div className="overview-secondary"><NewsCard preferences={preferences} savePreferences={savePreferences} /><section className="quick-routes"><h2>Make something better</h2>{[['skills', 'Your skills', 'Read, enhance and organize'], ['memory-review', 'Your memory', 'Keep instructions clear and scoped'], ['convert', 'Your documents', 'Turn files into readable Markdown']].map(([page, title, subtitle]) => <button key={page} onClick={() => navigate(page)}><strong>{title} →</strong><span>{subtitle}</span></button>)}</section></div></div>
  </>;
}
export function ExperienceSettings({ preferences, savePreferences }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const save = async patch => { setBusy(true); setError(''); try { await savePreferences(patch); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="wb-card"><h2>Your workspace experience</h2><p>Simple by default. Details whenever you need them.</p>{[['showDetails', 'Always show resource paths and technical details'], ['sessionsEnabled', 'Allow local session metadata insights'], ['newsEnabled', 'Fetch official release headlines for my tools']].map(([key, label]) => <label className="wb-check" key={key}><input type="checkbox" disabled={busy} checked={!!preferences[key]} onChange={e => void save({ [key]: e.target.checked })} />{label}</label>)}<p className="wb-muted">Session summaries stay in memory and exclude conversations. News is cached locally; AI only sends selected content when you start a job.</p>{error && <Notice error>{error}</Notice>}</section>;
}
export function EnhanceDialog({ resource, preferences, close, onReview, autoStart = true, guidance }) {
  const [settings, setSettings] = useState(() => settingsFromPreferences(preferences)), [goal, setGoal] = useState(guidance || 'Improve clarity, remove unnecessary repetition, preserve all essential constraints and examples, and keep project-specific guidance in its proper scope. Make a minimal useful edit.'), [advanced, setAdvanced] = useState(!autoStart), [error, setError] = useState('');
  const state = useAIJob(), once = useRef(false), result = state.job?.result;
  useEffect(() => { if (autoStart && !once.current) { once.current = true; void state.start('ai.propose', { id: resource.id, feedback: goal, settings }); } }, []);
  return <Dialog title={`Enhance ${resource.name}`} wide close={close}><p>Using {settings.provider === 'auto' ? 'your first compatible engine' : settings.provider} · {settings.model || 'saved model or engine default'}. The proposal uses the saved file; changes are reviewed before saving.</p><div className="wb-actions"><Button disabled={state.busy} onClick={() => setAdvanced(!advanced)}>Choose engine & model</Button><Button primary disabled={state.busy || !goal.trim()} onClick={() => state.start('ai.propose', { id: resource.id, feedback: goal, settings })}>{result ? 'Generate another proposal' : 'Enhance with AI'}</Button></div>{advanced && <div className="advanced-panel"><Field label="Improvement goal"><textarea value={goal} onChange={e => setGoal(e.target.value)} /></Field><AIControls value={settings} change={setSettings} /></div>}
    {state.error && <Notice error>{state.error}</Notice>}{error && <Notice error>{error}</Notice>}{state.job && <p role="status">{state.job.status} · {state.job.progress}</p>}{state.job?.error && <Notice error>{state.job.error}</Notice>}{state.busy && <Button onClick={state.cancel}>Cancel enhancement</Button>}
    {result?.candidate !== undefined && <><p>{result.rationale}</p><div className="wb-diff"><section><h3>Saved source</h3><pre>{state.job.source.content}</pre></section><section><h3>Proposed improvement</h3><pre>{result.candidate}</pre></section></div><Button primary onClick={async () => { try { const current = await request('resource.read', { id: resource.id, parked: false }); if (current.revision !== state.job.source.revision) throw Error('This file changed since the proposal. Generate a new proposal from the current source.'); onReview(result.candidate, state.job.source.revision); } catch (e) { setError(e.message); } }}>Review & save in editor</Button><p>{result.provenance} · {Number.isFinite(result.cost) ? `$${result.cost.toFixed(4)} reported` : 'Cost not reported / no model run'}</p></>}
  </Dialog>;
}
export function ObserverSettings() {
  const [provider, setProvider] = useState('Cursor'), [preview, setPreview] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [reviewed, setReviewed] = useState(false);
  const prepare = async action => { setBusy(true); setError(''); setPreview(null); setReviewed(false); try { setPreview(await request('observer.preview', { provider, action })); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="wb-card"><h2>Local activity observer</h2><p>Record future tool activity when native transcripts omit it. Cursor gains session and MCP call evidence; Claude can record instruction-load events. Codex is read through its native session logs.</p><p className="wb-muted">The observer keeps session IDs, tool names, timestamps, model IDs and file references on this machine. It excludes prompts, tool arguments and results. Existing hooks are preserved. Relaunch the harness after installation. If you move AIOS, install the observer again to update its executable path.</p>
    <Field label="Observer harness"><select disabled={busy} value={provider} onChange={e => { setProvider(e.target.value); setPreview(null); }}><option>Cursor</option><option>Claude Code</option></select></Field><div className="wb-actions"><Button disabled={busy} onClick={() => prepare('install')}>Preview observer installation</Button><Button disabled={busy} onClick={() => prepare('remove')}>Preview observer removal</Button></div>
    {error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}
    {preview && <><h3>{preview.action === 'install' ? 'Install' : 'Remove'} {preview.provider} observer</h3><p className="wb-path">{preview.path}</p><div className="wb-diff"><section><h3>Current hooks configuration</h3><pre>{preview.before}</pre></section><section><h3>Proposed configuration</h3><pre>{preview.after}</pre></section></div><label className="wb-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the observer and preserved hooks</label><Button primary disabled={!reviewed || busy} onClick={async () => { setBusy(true); setError(''); try { await request('observer.apply', { provider, action: preview.action, previewRevision: preview.previewRevision }); setMessage(`Observer ${preview.action === 'install' ? 'installed. New sessions can now record activity.' : 'removed. Existing local activity remains available.'}`); setPreview(null); } catch (e) { setError(e.message); setReviewed(false); } finally { setBusy(false); } }}>Apply observer changes</Button></>}
  </section>;
}
